define two language items
otherwise we won't be able to compile because of

```
error: language item required, but not found: `panic_fmt`
error: language item required, but not found: `eh_personality`
```